### ISSUE TITLE
Check undocumented commands

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/docs#2]
Check if all commands are converted and also check which commands are undocumented. Add issues for all these commands separately.

Mainly a TODO for me personally just here as a reminder.

**Comment by torusrxxx** [comment]
For some unknown reasons, some commands cannot be automatically converted and have to convert by hand. By now I have added all documented commands here. Please check it against the previous help.
"Plugins" section cannot be automatically converted. I'm converting them manually.

**Comment by mrexodia** [comment]
I was thinking about pasting the text in some rich text editor, which gives
nice markup which can then be converted to Markdown. Still manual work, but
not as bad as having to convert everything fully by hand...

**Comment by torusrxxx** [comment]
All documents are migrated here now.(except the useless "Scripting" page)
Please check it again and then we can abandon the old help system.

**Comment by mrexodia** [comment]
Alright I will check it as soon as possible! I still have to figure out how
to generate a chm file (or something like it) though sphinx. Then I will
migrate to the new help system.

**Comment by mrexodia** [comment]
I added all undocumented commands that require documentation. Some commands should **not** be documented (since they are for developers). These are `bench, dprintf, capstone, visualize, meminfo`

Other commands are part of an unfinished project: `setstr, getstr, copystr`
