### ISSUE TITLE
jQuery script error when clicking links in documentation

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/docs#27]
I get a script error messagebox popup when running the x64dbgdocs.chm

Hopefully its not something i did when adding in the callback structure info.

Maybe someone can re run the make and check all is ok

Here is a screenshot to show the script error messagebox:

![](https://s20.postimg.org/tzwdm3xzx/Screenshot_2.png)

**Comment by mrexodia** [comment]
I think this is fixed on the build server.

**Comment by mrfearless** [comment]
ok thats good then.

**Comment by mrexodia** [comment]
Yeah, just checked again. If you run makechm.bat it should work fine.

Op wo 20 jul. 2016 om 14:09 schreef fearless <notifications@github.com>:
