### ISSUE TITLE
"String formatting" link in "msg" and "msgyn" commands are broken in CHM files

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/docs#60]
These commands can be documented in rst format, like "log.rst", to support internal linking.

**Comment by mrexodia** [comment]
http://x64dbg.readthedocs.io/en/latest/commands/script-commands/msgyn.html here
it works fine, probably the local version is not the same. I use a plugin
to link markdown documents correctly. I will check what the problem is.

**Comment by mrexodia** [comment]
Okay, it has been fixed. There was a bug in `recommonmark-0.4.0` with path separator, see https://github.com/rtfd/recommonmark/blob/master/recommonmark/transform.py#L71
