### ISSUE TITLE
http://help.x64dbg.com/en/latest/gui/views/index.html is down

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/docs#77]
http://help.x64dbg.com/en/latest/gui/views/index.html is down

**Comment by torusrxxx** [comment]
Error 1014 Ray ID: 0123456789abcdef • 2020-07-05 00:00:00 UTC
CNAME Cross-User Banned
What happened?

You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.
What can I do?

If you are interested in learning more about Cloudflare, please visit our website.

**Comment by mrexodia** [comment]
Very strange, because for me everything is working fine...

**Comment by torusrxxx** [comment]
Cloudflare, we have a problem.

**Comment by mrexodia** [comment]
Is this still an issue for you @torusrxxx ? I can try contacting cloudflare to ask them about it.

**Comment by torusrxxx** [comment]
Yes, it happens after the link is opened and then refreshed. But I don't really visit https://help.x64dbg.com , most of the time I just view the CHM or use https://x64dbg.readthedocs.io .
