### ISSUE TITLE
.readthedocs.yaml will be required on September 25, 2023

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/docs#93]
`.readthedocs.yaml` version 2 will be required to build the documentation on September 25, 2023.
https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by mrexodia** [comment]
That’s quite unfortunate for us since we are using some ancient version to generate the CHM…

**Comment by mrexodia** [comment]
Done, I followed the transition guide and ran a test build everything seems fine! Likely soon they will deprecate Python 2.7 support, which might become problematic for building the CHM but we'll see when that happens.
